import backend.Show;
import backend.* ; 
import backend.Booking ; 

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.ZoneId;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;





/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class MyRooms extends javax.swing.JFrame {
        String username ,bname,nop,nor,hname,city ;  Date ci,co ; RoomType rtype ;  // hname is hotelname and rtype is roomtype and bname is booking name  .. 
    /**
     * Creates new form MyRooms
     */
    public MyRooms() {
        initComponents();
    }
    
    public MyRooms(String username , String Bname , String no_of_people ,String no_of_rooms, String hotelname,Date ci , Date co,String roomtype , String city ) {
        
        this.username=username ; 
        bname=Bname ; 
        nop=no_of_people ; 
        nor=no_of_rooms ; 
        hname=hotelname ; 
        this.ci=ci ; 
        this.co=co ; 
        if(roomtype.equals("SINGLE"))
            rtype=RoomType.SINGLE ; 
       else if(roomtype.equals("LUXURY"))
            rtype=RoomType.LUXURY; 
       else if(roomtype.equals("DOUBLE"))
            rtype=RoomType.DOUBLE ; 
        
       // System.out.print(roomtype+"  efs");  
        this.city=city ; 
        
      Random r = new Random() ; 
      initComponents() ; 
      jLabel1.setText(hotelname) ;
      jLabel7.setText(3+r.nextInt(2) + "") ; 
      jLabel9.setText(50+r.nextInt(50) + "") ; 
      DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); 
      System.out.println( dateFormat.format(ci)+" "+dateFormat.format(co) );
      
      try{  jLabel5.setText(""+ Show.findRooms(city , hotelname , roomtype, dateFormat.format(ci), dateFormat.format(co) ) ) ; }
      catch(Exception e){ e.printStackTrace(); ; }
      
      
      
      if(roomtype.equals("DOUBLE"))
      jLabel6.setText("SWIMMING POOL , WIFI , AC") ;
      
      else if(roomtype.equals("LUXURY"))
      jLabel6.setText("FREE_BREAKFAST , SWIMMING POOL , WIFI , AC , SPA") ;
      
      else 
      jLabel6.setText("WIFI , AC") ;
    
      jButton1.setEnabled(false);
      jButton3.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 900));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Hotel      name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 610, 97);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("No Of Rooms Available");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 216, 264, 56);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Amenities Available");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 367, 264, 60);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Ratings");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 516, 264, 58);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 220, 243, 56);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(382, 387, 510, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 520, 66, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Stars");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(460, 520, 107, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 0));
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(680, 530, 60, 16);

        jLabel10.setText("feedbacks");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(750, 520, 82, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jButton1.setText("Book ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(225, 777, 206, 87);

        jButton2.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(750, 20, 120, 60);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton3.setText("Enroll in Waiting List");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(600, 800, 264, 50);

        jButton4.setFont(new java.awt.Font("Tekton Pro", 3, 24)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(640, 20, 103, 60);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setText("Aadhaar Number ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(40, 671, 203, 52);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(412, 679, 364, 42);

        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Enter Your 12 digit Aadhaar no.");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 636, 203, 16);

        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("Press enter ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(804, 695, 90, 16);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Desktop\\programme codes\\OOP mini project\\himage.jpg")); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 900, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
              new sign_in().setVisible(true);
              this.dispose() ; // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                  if(Integer.parseInt(nor)<=Integer.parseInt(jLabel5.getText())){
                     User u = User.sendObject(username) ; 
                          
                          
                          
                          
                          for(int i=0 ; i<Integer.parseInt(nor) ; i++)
                          {   u.count++ ;
                              Booking b= null ;
                              b = u.makeBooking(u.count, bname, Integer.parseInt(nop), city, hname, rtype,Integer.parseInt(nor),Instant.ofEpochMilli(ci.getTime()).atZone(ZoneId.systemDefault()).toLocalDate(), Instant.ofEpochMilli(co.getTime()).atZone(ZoneId.systemDefault()).toLocalDate(),jTextField1.getText(),null);
                            
                          }
                          
                         u.makeBook(u.count,bname,Integer.parseInt(nop),city,hname,rtype,Integer.parseInt(nor),ci,co,jTextField1.getText(),null) ;
                         
                         
                          
                          
                          
                          
                          JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                           javax.swing.JOptionPane.showMessageDialog(frame,"Congrats !! you have successfully booked  and your refernce ID is : "+u.count+"   Note: your ref id will be shown in the previous bookings  ") ;
                           new User_page(username).setVisible(true) ;
                           this.dispose() ; } 
                  
                  else
                  {  
                       JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                           javax.swing.JOptionPane.showMessageDialog(frame,"You can not book as no of rooms available are less than what you require ") ; 
                  
                  
                  }
              // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            try {
                new Hotel_page(username,bname,nor,nop,rtype.toString(),city,ci,co).setVisible(true) ; 
                this.dispose() ; // TODO add your handling code here:
            } catch (Exception ex) {
                Logger.getLogger(MyRooms.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("inside MY rooms"); 
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
             if (jTextField1.getText().length()==12){
               jButton1.setEnabled(true);
               jButton3.setEnabled(true);}
             else{
                  jButton1.setEnabled(false);
                  jButton3.setEnabled(false);
             }
      // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                   if(Integer.parseInt(jLabel5.getText())==0)
                   {
                       JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                           javax.swing.JOptionPane.showMessageDialog(frame,"You have been suceessfully enrolled in the waiting list.. In previous bookings window  your booking will be displayed if no of  rooms you require get empty and your booking will be processsed  "  ) ; 
                   
                           User u = User.sendObject(username) ;
                          for(int i=0 ; i<Integer.parseInt(nor) ; i++)
                          {   u.count++ ;
                              Booking b= null ;
                              b = u.makeBooking(u.count, bname, Integer.parseInt(nop), city, hname, rtype,Integer.parseInt(nor),Instant.ofEpochMilli(ci.getTime()).atZone(ZoneId.systemDefault()).toLocalDate(), Instant.ofEpochMilli(co.getTime()).atZone(ZoneId.systemDefault()).toLocalDate(),jTextField1.getText(),null);
                            
                          }
                           
                   }

                        else 
                   {
                       JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                           javax.swing.JOptionPane.showMessageDialog(frame,"Sorry we can not enroll you in the waiting list as rooms are still available .. "  ) ; 
                   
                   }// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyRooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyRooms().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}

